language: ruby
script: "bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.4.0
- 2.3.3
- 2.2.3
- 2.1

gemfile:
- Gemfile.rails32
- Gemfile.rails40
- Gemfile.rails41
- Gemfile.rails42
- Gemfile.rails5

matrix:
  exclude:
    - rvm: 2.1
      gemfile: Gemfile.rails5
    - rvm: 2.4.0
      gemfile: Gemfile.rails32
    - rvm: 2.4.0
      gemfile: Gemfile.rails40
    - rvm: 2.4.0
      gemfile: Gemfile.rails41
    - rvm: 2.4.0
      gemfile: Gemfile.rails42

before_install:
  - gem update bundler
